version: "3.8"

services:
  db:
    image: postgres
    restart: always
#    volumes:
#      - ./postgresql/data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=db_book_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
#    build: .
    image: nexus07/book_store_deep_longeviry
#    command: python manage.py runserver 0.0.0.0:8000
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_project
    ports:
      - "8000:8000"
    depends_on:
      - db
