# Generated by Django 3.2 on 2021-04-09 16:21

from django.db import migrations
from django.contrib.auth import get_user_model
# from rest_framework.authtoken.models import Token

def add_token_for_user(apps, schema_editor):
	# User = get_user_model()
	User = apps.get_model("app", "User")
	Token = apps.get_model("authtoken", "Token")

	token = Token(user=User.objects.get(username='admin'), key='f4f9b4af1f8357d21e27db19af3fa497cd0ac9a7')
	token.save()
	print(f'Token {token.key}')


class Migration(migrations.Migration):
	dependencies = [
		('app', '0001_initial'),
		('authtoken', '0003_tokenproxy'),
		('sessions', '0001_initial'),
	]

	operations = [
		migrations.RunPython(add_token_for_user),
	]
